version: '3.8'

services:
  azure-board-agents:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AI_FOUNDRY_ENDPOINT=${AI_FOUNDRY_ENDPOINT}
      - AI_FOUNDRY_ASSISTANT_ID=${AI_FOUNDRY_ASSISTANT_ID}
      - AI_FOUNDRY_TESTCASES_ASSISTANT_ID=${AI_FOUNDRY_TESTCASES_ASSISTANT_ID}
      - AI_FOUNDRY_DEV_TASKS_ASSISTANT_ID=${AI_FOUNDRY_DEV_TASKS_ASSISTANT_ID}
      - AZURE_DEVOPS_PAT=${AZURE_DEVOPS_PAT}
      - AZURE_DEVOPS_ORGANIZATION_URL=${AZURE_DEVOPS_ORGANIZATION_URL}
      - AZURE_DEVOPS_PROJECT=${AZURE_DEVOPS_PROJECT}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s